--- #YAML:1.0
name:               sastatd
version:            0.03
abstract:           SpamAssassin statistic collecting server
author:
    - Oleg A. Mamontov <oleg@mamontov.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    JSON::Any:         0
    Log::Dispatch:     2.26
    Pid::File::Flock:  0
    POE:               0
    Test::More:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
